---
title: "insectai_to_camtrapdp"
author: 
- "Sanne Govaert"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(dplyr)
library(frictionless)
library(camtrapdp)
```

# Import data

```{r}
project_name <- "my_project"
file_name <- "my_file.csv"
data <- read.csv(here::here("data", "raw", project_name, file_name))
```

# Create resources

## Create deployments resource

```{r}
deployments <-
  data |> 
  dplyr::mutate(
    deploymentID = NA_character_, # Required
    locationID = NA_character_,
    locationName = NA_character_,
    latitude = NA_real_, # Required
    longitude = NA_real_, # Required
    coordinateUncertainty = NA_integer_,
    deploymentStart = NA_character_, # Required | YYYY-MM-DDThh:mm:ssZ or YYYY-MM-DDThh:mm:ss±hh:mm
    deploymentEnd = NA_character_, # Required | YYYY-MM-DDThh:mm:ssZ or YYYY-MM-DDThh:mm:ss±hh:mm
    setupBy = NA_character_,
    cameraID = NA_character_,
    cameraModel = NA_character_,
    cameraDelay = NA_integer_,
    cameraHeight = NA_real_,
    cameraDepth = NA_real_,
    cameraTilt = NA_integer_,
    cameraHeading = NA_integer_,
    detectionDistance = NA_real_,
    timestampIssues = NA_character_,
    attractantUse = NA,
    atttractantTypr = NA_character_,
    featureType = NA_character_,
    habitat = NA_character_,
    deploymentGroups = NA_character_,
    deploymentTags = NA_character_,
    deploymentComments = NA_character_,
    .keep = "none"
  ) |> 
  dplyr::arrange(deploymentID)
```

## Create media resource

```{r}
media <-
  data |> 
  dplyr::mutate(
    mediaID = NA_character_, # Required
    deploymentID = NA_character_, # Required
    captureMethod = NA_character_,
    timestamp = NA_character_, # Required | YYYY-MM-DDThh:mm:ssZ or YYYY-MM-DDThh:mm:ss±hh:mm
    filePath = NA_character_, # Required
    filePublic = NA, # Required
    fileName = NA_character_,
    fileMediatype = NA_character_, # Required
    exifData = NA_character_,
    favorite = NA_character_,
    mediaComments = NA_character_,
    .keep = "none"
  ) |> 
  dplyr::arrange(mediaID) |>
  dplyr::distinct()
```

## Create observations resource

```{r}
observations <-
  data |> 
  dplyr::mutate(
    observationID = NA_character_, # Required
    deploymentID = NA_character_, # Required
    mediaID = NA_character_,
    eventID = NA, # If empty, set to NA to be able to use read_camtrapdp(), see https://github.com/inbo/camtrapdp/issues/162
    eventStart = NA_character_, # Required
    eventEnd = NA_character_, # Required
    observationLevel = NA_character_, # Required
    observationType = NA_character_, # Required 
    cameraSetupType = NA_character_,
    scientificName = NA_character_,  # Required
    count = NA_integer_,
    lifeStage = NA_character_,
    sex = NA_character_,
    behavior = NA_character_,
    individualID = NA_character_,
    individualPositionRadius = NA_real_,
    individualPositionAngle = NA_real_,
    individualSpeed = NA_real_,
    bboxX = NA_real_,
    bboxY = NA_real_,
    bboxWidth = NA_real_,
    bboxHeight = NA_real_,
    classificationMethod = NA_character_,
    classifiedBy = NA_character_,
    classificationTimestamp = NA_character_,
    classificationProbability = NA_real_,
    observationTags = .data$tags,
    observationComments = NA_character_,
    .keep = "none"
  ) |> 
  dplyr::arrange(observationID)
```

# Create data package

```{r}
insectai <-
  frictionless::create_package() |>
  add_resource(resource_name = "deployments", data = deployments) |>
  add_resource(resource_name = "media", data = media) |>
  add_resource(resource_name = "observations", data = observations) |>
  append(c(
    name = "camtrap-dp-insectai-example-dataset", # Required
    profile = "https://raw.githubusercontent.com/tdwg/camtrap-dp/refs/heads/insectai/camtrap-dp-profile.json", # Required
    id = NULL,
    created = format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"), # Required
    title = NULL,
    description = NULL,
    version = "1.0",
    keywords = NULL,
    image = NULL,
    homepage = NULL,
    sources = NULL,
    bibliographicCitation = NULL,
    coordinatePrecision = NULL,
    spatial = NULL, # Required, but keep this empty, this comes later
    temporal = NULL, # Required, but keep this empty, this comes later
    taxonomic = NULL, # Required, but keep this empty, this comes later
    relatedIdentifiers = NULL,
    references = NULL
  )) |>
  frictionless::create_package()

insectai$contributors <- list( # Required
  list(
    title = NULL,
    email = NULL,
    path = NULL,
    role = NULL,
    organization = NULL
  )
)

insectai$licenses <- list(
  list(
    name = "CC0-1.0",
    scope = "data" # Required
  ),
  list(
    path = "http://creativecommons.org/licenses/by/4.0/",
    scope = "media" # Required
  )
)

insectai$project <- list( # Required
  # id = "",
  title = NULL, # Required
  # acronym = "",
  description = NULL,
  protocolType = NULL, # Required
  samplingDesign = NULL, # Required
  # path = NULL,
  captureMethod = NULL, # Required
  individualAnimals = NULL, # Required
  observationLevel = NULL # Required
)
```

## Create taxonomy

```{r}
map_taxonomy <- function(taxonomy) {
  list(
    scientificName = taxonomy$scientificName, # Adapt this!
    vernacularNames = list(
      eng = taxonomy$EnglishName # Adapt this!
      )
  )
}
```

```{r}
taxonomy_list <- apply(taxonomy, 1, as.list) # First create taxonomy df, then adapt this!
insectai$taxonomic <- purrr::map(taxonomy_list, map_taxonomy)
```

# Write Data Package

```{r}
frictionless::write_package(insectai, here::here("data", "interim", project_name))
```

# Read with camtrapdp

This automatically updates the spatial, temporal and taxonomic coverage in the metadata, based on the data.

```{r}
insectai_dp <- camtrapdp::read_camtrapdp(here::here("data", "interim", project_name, "datapackage.json"))
```

# Write Camtrap DP

```{r}
camtrapdp::write_camtrapdp(insectai_dp, here::here("data", "processed", project_name))
```
